/**
 * Session-level media cache (CRB-02).
 *
 * Holds generated bytes for the current app session so a fresh candidate can
 * be selected (carousel, compare, downstream) before it is saved to the
 * generations folder — or when no generations folder is configured at all.
 * Disk remains the durable source; this cache never replaces it.
 */

interface SessionEntry {
  dataUrl: string;
  bytes: number;
}

/** Small enough to stay resident; eviction is oldest-first. */
const MAX_ENTRIES = 40;
const MAX_BYTES = 64 * 1024 * 1024;

const cache = new Map<string, SessionEntry>();
let totalBytes = 0;

function entryBytes(dataUrl: string): number {
  return dataUrl.length;
}

export function rememberSessionMedia(id: string, dataUrl: string): void {
  const existing = cache.get(id);
  if (existing) {
    totalBytes -= existing.bytes;
    cache.delete(id);
  }
  const bytes = entryBytes(dataUrl);
  cache.set(id, { dataUrl, bytes });
  totalBytes += bytes;
  while ((cache.size > MAX_ENTRIES || totalBytes > MAX_BYTES) && cache.size > 0) {
    const oldest = cache.keys().next();
    if (oldest.done) break;
    const removed = cache.get(oldest.value);
    cache.delete(oldest.value);
    if (removed) totalBytes -= removed.bytes;
  }
}

/** Session bytes first; disk loader stays the fallback for older entries. */
export function readSessionMedia(id: string): string | null {
  return cache.get(id)?.dataUrl ?? null;
}

export function clearSessionMedia(): void {
  cache.clear();
  totalBytes = 0;
}
